# Generated by Django 5.0.1 on 2024-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todoitem_description_todoitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='description',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
